sonar.projectKey=AyushHarduth123_international-portal-api
sonar.projectName=AtlasPay (INSY7314e)
sonar.organization=ayushharduth123
sonar.host.url=https://sonarcloud.io

sonar.sources=payments-api, payments-client/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/.vite/**,**/*.min.js,**/*.map,**/*.lock,**/certs/**

sonar.sourceEncoding=UTF-8
sonar.javascript.file.suffixes=.js,.jsx,.ts,.tsx
